apiVersion: v1
kind: Service
metadata:
  name: read-text-service
spec:
  selector:
    app: read-text
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: read-text
spec:
  selector:
    matchLabels:
      app: read-text
  replicas: 2
  template:
    metadata:
      labels:
        app: read-text
    spec:
      containers:
      - name: read-text
        image: piyush9090/read-text
        imagePullPolicy: Always
        ports:
        - containerPort: 5000